const r = require("raylib")
const WINDOW_WIDTH = 900;
const WINDOW_HEIGHT = 700;
const FPS = 60;
const WINDOW_COLOR = r.BLACK;

const SCANNER_1_WIDTH = WINDOW_WIDTH / 15;
const SCANNER_2_WIDTH = WINDOW_WIDTH / 15;
const VERTICAL_SCANNER_1_HEIGHT = WINDOW_HEIGHT / 15;

const PARTICLE_1_WIDTH = WINDOW_WIDTH / 10;
const PARTICLE_2_WIDTH = WINDOW_WIDTH / 25;
const HORIZONTAL_PERTICAL_1_HEIGHT = WINDOW_HEIGHT / 25;

module.exports = { WINDOW_WIDTH, WINDOW_HEIGHT, FPS, WINDOW_COLOR, SCANNER_1_WIDTH, SCANNER_2_WIDTH, VERTICAL_SCANNER_1_HEIGHT, PARTICLE_1_WIDTH, PARTICLE_2_WIDTH, HORIZONTAL_PERTICAL_1_HEIGHT }