const r = require("raylib")
const WINDOW_WIDTH = 600;
const WINDOW_HEIGHT = 500;
const FPS = 60;
const WINDOW_COLOR = r.BLACK;

const SCANNER_WIDTH = WINDOW_WIDTH / 10;
const PARTICLE_WIDTH = WINDOW_WIDTH / 5;

module.exports = { WINDOW_WIDTH, WINDOW_HEIGHT, FPS, WINDOW_COLOR, SCANNER_WIDTH, PARTICLE_WIDTH }